# Goコードの書き方 - The Go Programming Language
# http://golang-jp.org/doc/code.html
# 
# これからGoを始める人のためのTips集
# http://blog.wacul.co.jp/blog/2014/08/22/go/
# 
# Vagrant+AnsibleでGo環境を構築し、せっかくなのでAWS SDK for Goを試してみる。
# http://qiita.com/itayan/items/b41f8541892e693aeb0a
---
- hosts: default
  sudo: false
  vars:
    goversion: "1.5.1"
    goroot: "/usr/local"
    gopath: "/home/vagrant/go"
    apppath: "{{ gopath }}/src/godemo"
  environment:
    HOME: /home/vagrant
    GOPATH: "{{ gopath }}"
    PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin:{{ gopath }}/bin
  tasks:
  - name: update apt-get
    apt: update_cache=yes
    sudo: yes
  - name: upgrade apt-get
    apt: upgrade=yes
    sudo: yes
  - name: install dependence packages
    apt: name={{ item.name }} state=installed
    with_items:
      - { name: git }
      - { name: redis-server }
      - { name: postgresql }
    sudo: yes
  - name: update postgres config for development
    replace: dest=/etc/postgresql/9.1/main/pg_hba.conf regexp='peer\|md5' replace='trust'
    sudo: yes
    register: postgres_config
  - name: restart postgresql
    service: name=postgresql state=restarted
    sudo: yes
    when: postgres_config.changed
  - name: check synced folder owner is vagrant
    stat: path={{ gopath }}
    register: synced_folder
  - name: override synced folder owner to Vagrant
    shell: chown vagrant:vagrant -R {{ gopath }}
    sudo: yes
    when: synced_folder.stat.pw_name != 'vagrant'
  - name: check Go exists
    stat: path={{ goroot }}/go
    register: go_exists
  - name: check Go version
    shell: go version | awk '{ print $3 }'
    register: go_version_matched
    ignore_errors: yes
    when: go_exists.stat.exists
  - name: get a go
    shell: wget https://storage.googleapis.com/golang/go{{ goversion }}.linux-amd64.tar.gz
    when: not go_exists.stat.exists or go_version_matched.stdout.find('go{{ goversion }}')
  - name: extract files from an archive
    shell: sudo tar -C {{ goroot }} -xzf go{{ goversion }}.linux-amd64.tar.gz
    when: not go_exists.stat.exists or go_version_matched.stdout.find('go{{ goversion }}')
  - name: set GOPATH
    lineinfile: dest=/home/vagrant/.bash_profile state=present insertafter=EOF regexp='export GOPATH=' line='export GOPATH={{ gopath }}'
  - name: set PATH to Go bin
    lineinfile: dest=/home/vagrant/.bash_profile state=present insertafter=EOF regexp='{{ goroot }}/go/bin:' line='export PATH=$PATH:{{ goroot }}/go/bin:$GOPATH/bin'
  - name: get godep
    shell: go get github.com/kr/godep
  - name: save go dependencies
    shell: cd {{ apppath }} && go get && godep save
